import { RadialBar, RadialBarChart, ResponsiveContainer } from 'recharts'
import type { PredictionResult } from '../lib/api'
// RadialBar, RadialBarChart, ResponsiveContainer used for FRS gauge below
import './ResultPanel.css'

interface Props {
  result: PredictionResult | null
  loading: boolean
  error: string | null
}

const RISK_CONFIG = {
  Normal:        { color: '#16a34a', bg: '#f0fdf4', border: '#bbf7d0', icon: '✓', label: 'Low Risk' },
  Suspect:       { color: '#d97706', bg: '#fffbeb', border: '#fde68a', icon: '!',  label: 'Watch Closely' },
  Pathological:  { color: '#dc2626', bg: '#fef2f2', border: '#fecaca', icon: '!!', label: 'High Risk' },
}

const UNCERTAINTY_CONFIG = {
  low:      { label: 'High Confidence', color: '#16a34a' },
  moderate: { label: 'Moderate Confidence', color: '#d97706' },
  high:     { label: 'Low Confidence', color: '#dc2626' },
}

export function ResultPanel({ result, loading, error }: Props) {
  if (loading) return <LoadingState />
  if (error)   return <ErrorState message={error} />
  if (!result) return <EmptyState />

  const cfg = RISK_CONFIG[result.risk_label]
  const unc = UNCERTAINTY_CONFIG[result.uncertainty]

  const probData = [
    { name: 'Normal',       value: Math.round(result.prob_normal * 100),       fill: '#16a34a' },
    { name: 'Suspect',      value: Math.round(result.prob_suspect * 100),      fill: '#d97706' },
    { name: 'Pathological', value: Math.round(result.prob_pathological * 100), fill: '#dc2626' },
  ]

  return (
    <div className="result-panel">
      {/* Risk classification header */}
      <div className="result-risk" style={{ background: cfg.bg, borderColor: cfg.border }}>
        <div className="result-risk__icon" style={{ background: cfg.color }}>
          {cfg.icon}
        </div>
        <div className="result-risk__body">
          <div className="result-risk__tag" style={{ color: cfg.color }}>{cfg.label}</div>
          <div className="result-risk__label" style={{ color: cfg.color }}>{result.risk_label}</div>
          <div className="result-risk__confidence">
            Confidence: <strong>{(result.confidence * 100).toFixed(1)}%</strong>
            <span className="result-risk__uncertainty" style={{ color: unc.color }}>
              &nbsp;&bull;&nbsp;{unc.label}
            </span>
          </div>
        </div>
      </div>

      {/* Probability bars */}
      <div className="result-section">
        <h3 className="result-section__title">Risk Probability</h3>
        <div className="prob-bars">
          {probData.map(d => (
            <ProbBar key={d.name} label={d.name} value={d.value} color={d.fill} />
          ))}
        </div>
      </div>

      {/* Fetal Reserve Score */}
      <div className="result-section">
        <h3 className="result-section__title">Fetal Reserve Score</h3>
        <div className="frs-row">
          <div className="frs-gauge">
            <ResponsiveContainer width={120} height={120}>
              <RadialBarChart
                cx="50%" cy="50%"
                innerRadius="65%" outerRadius="90%"
                startAngle={225} endAngle={-45}
                data={[{ value: 100, fill: '#e5e7eb' }, { value: result.fetal_reserve_score, fill: frsColor(result.fetal_reserve_score) }]}
              >
                <RadialBar dataKey="value" background={false} />
              </RadialBarChart>
            </ResponsiveContainer>
            <div className="frs-gauge__value" style={{ color: frsColor(result.fetal_reserve_score) }}>
              {result.fetal_reserve_score}
            </div>
            <div className="frs-gauge__label">/ 100</div>
          </div>
          <div className="frs-info">
            <div className="frs-info__grade" style={{ color: frsColor(result.fetal_reserve_score) }}>
              {frsGrade(result.fetal_reserve_score)}
            </div>
            <p className="frs-info__desc">{frsDesc(result.fetal_reserve_score)}</p>
          </div>
        </div>
      </div>

      {/* Clinical explanations */}
      {result.explanation.length > 0 && (
        <div className="result-section">
          <h3 className="result-section__title">Key Findings</h3>
          <ul className="findings-list">
            {result.explanation.map((e, i) => (
              <li key={i} className="findings-list__item">
                <span className="findings-list__dot" style={{ background: cfg.color }} />
                {e}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Uncertainty note */}
      <div className="result-section result-section--muted">
        <p className="result-disclaimer">
          This analysis is generated by FetalyzeAI v4, a research-stage model. It is not a clinical
          diagnosis. Always consult a qualified obstetrician or midwife.
        </p>
      </div>
    </div>
  )
}

function ProbBar({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div className="prob-bar">
      <div className="prob-bar__header">
        <span className="prob-bar__label">{label}</span>
        <span className="prob-bar__value" style={{ color }}>{value}%</span>
      </div>
      <div className="prob-bar__track">
        <div
          className="prob-bar__fill"
          style={{ width: `${value}%`, background: color }}
        />
      </div>
    </div>
  )
}

function frsColor(score: number) {
  if (score >= 70) return '#16a34a'
  if (score >= 40) return '#d97706'
  return '#dc2626'
}
function frsGrade(score: number) {
  if (score >= 70) return 'Good Reserve'
  if (score >= 40) return 'Reduced Reserve'
  return 'Low Reserve'
}
function frsDesc(score: number) {
  if (score >= 70) return 'Fetus appears to be tolerating labour well. Reassuring pattern.'
  if (score >= 40) return 'Some signs of reduced fetal tolerance. Close monitoring recommended.'
  return 'Significant signs of reduced fetal reserve. Urgent clinical review advised.'
}

function EmptyState() {
  return (
    <div className="result-empty">
      <div className="result-empty__icon">
        <svg viewBox="0 0 48 48" fill="none">
          <circle cx="24" cy="24" r="22" stroke="#e5e7eb" strokeWidth="2" fill="#f9fafb"/>
          <path d="M14 24h5l3-8 4 16 3-8h5" stroke="#d1d5db" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      </div>
      <h3 className="result-empty__title">No analysis yet</h3>
      <p className="result-empty__desc">
        Adjust the CTG parameters on the left and click <strong>Run CTG Analysis</strong> to get a risk classification.
      </p>
      <p className="result-empty__hint">Use a preset to get started quickly.</p>
    </div>
  )
}

function LoadingState() {
  return (
    <div className="result-loading">
      <div className="result-loading__spinner" />
      <p>Analysing CTG pattern…</p>
    </div>
  )
}

function ErrorState({ message }: { message: string }) {
  return (
    <div className="result-error">
      <svg viewBox="0 0 20 20" fill="currentColor" width="20" height="20">
        <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clipRule="evenodd"/>
      </svg>
      <div>
        <strong>Analysis failed</strong>
        <p>{message}</p>
      </div>
    </div>
  )
}
